{{- if .Values.service.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "default-chart.fullname" .  }}
  labels:
    {{- include "default-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      
  selector:
    {{- include "default-chart.selectorLabels" . | nindent 4 }}
{{- end }}
