apiVersion: v1
kind: Service
metadata:
  name: {{ include "datora-site-server.fullname" . }}
  labels:
    {{- include "datora-site-server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      
  selector:
    {{- include "datora-site-server.selectorLabels" . | nindent 4 }}
