image: "registry.gitlab.com/fenix-pagtel/charts:helm"

stages:
  - lint
  - deploy

check:
  stage: lint
  script:
    - helm lint helm-chart-sources/*

pages:
  stage: deploy
  script:
    - mkdir -p ./public
    - "echo \"User-Agent: *\nDisallow: /\" > ./public/robots.txt"
    - helm package helm-chart-sources/* --destination ./public
    - helm repo index --url https://${CI_PROJECT_NAMESPACE}.gitlab.io/${CI_PROJECT_NAME} .
    - mv *.tgz ./public
    - mv index.yaml ./public
  artifacts:
    paths:
      - public
  only:
    - main
