image: "$CI_REGISTRY_IMAGE:helm"

stages:
  - lint
  - deploy

lint:
  stage: lint
  script:
    - helm lint templates/*

pages:
  stage: deploy
  script:
    - mkdir -p ./public/templates
    - cp -r ./raw ./public/
    - "echo \"User-Agent: *\nDisallow: /\" > ./public/robots.txt"
    - helm package templates/* --destination ./public/templates
    - helm repo index --url https://${CI_PROJECT_NAMESPACE}.gitlab.io/${CI_PROJECT_NAME}/templates ./public/templates
  artifacts:
    paths:
      - public
  only:
    - main
