image: "$CI_REGISTRY_IMAGE:helm"

stages:
  - lint
  - deploy

lint:
  stage: lint
  script:
    - helm lint charts/*

pages:
  stage: deploy
  script:
    - mkdir -p ./public/charts
    - cp -r ./raw ./public/
    - "echo \"User-Agent: *\nDisallow: /\" > ./public/robots.txt"
    - helm package charts/* --destination ./public/charts
    - helm repo index --url https://${CI_PROJECT_NAMESPACE}.gitlab.io/${CI_PROJECT_NAME}/charts ./public/charts
  artifacts:
    paths:
      - public
  only:
    - main
