image: "$CI_REGISTRY_IMAGE:helm"

stages:
  - lint
  - deploy

lint:
  stage: lint
  script:
    - helm lint development/*

pages:
  stage: deploy
  script:
    - mkdir -p ./public/development
    - "echo \"User-Agent: *\nDisallow: /\" > ./public/robots.txt"
    - helm package development/* --destination ./public/development
    - helm repo index --url https://${CI_PROJECT_NAMESPACE}.gitlab.io/${CI_PROJECT_NAME}/development ./public/development
  artifacts:
    paths:
      - public
  only:
    - main
