---
apiVersion: v1
kind: ConfigMap
metadata:
  name: recharge-and-plan-gateway
data:
  # SERVER
  NODE_ENV: ""
  BASE_URI: ""
  PORT: ""
  # DATABASE
  DB_DIALECT: ""
  DB_HOST: ""
  DB_NAME: ""
  DB_RECHARGE_NAME: ""
  DB_PORT: ""
  # RABBIT
  RABBIT_HOST: ""
  RABBIT_PORT: ""
  # API
  API_MAIL: ""
  API_AUTHENTICATION: ""
  API_FINANCIAL_TRANSACTION: ""
