---
apiVersion: v1
kind: ConfigMap
metadata:
  name: card-management-microservice
data:
  # SERVER
  NODE_ENV: ""
  BASE_URI: ""
  PORT: ""
  # DATABASE
  DB_DIALECT: ""
  DB_HOST: ""
  DB_NAME: ""
  DB_PORT: ""
  # RABBIT
  RABBIT_HOST: ""
  RABBIT_PORT: ""
  # APIS
  API_AUTHENTICATOR: ""
