apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mssql-db.fullname" . }}
  labels:
    {{- include "mssql-db.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "mssql-db.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "mssql-db.selectorLabels" . | nindent 8 }}
    spec:

      initContainers:
        - name: volume-permissions
          image: busybox
          command: ["sh", "-c", "chown -R 10001:0 /var/opt/mssql"]
          volumeMounts:
          - mountPath: "/var/opt/mssql"
            name: sql-storage

      volumes:
        - name: sql-storage
          persistentVolumeClaim:
            claimName: node-shared-mssql-volume-claim

      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "mssql-db.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          volumeMounts:
            - mountPath: "/var/opt/mssql/data"
              name: sql-storage
          ports:
            - name: sqlport
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          env:
            - name: ACCEPT_EULA
              value: "Y"

            - name: SA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mssql-db
                  key: SA_PASSWORD

          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
