apiVersion: v1
entries:
  default-chart:
  - apiVersion: v2
    created: "2023-07-04T15:48:19.26186136Z"
    description: Default Helm chart
    digest: 4a1b5e4836ae1b5f139d8302bfdceda4f1b7510fcfb7865acda25ac131f7acfb
    name: default-chart
    type: application
    urls:
    - default-chart-1.0.0.tgz
    version: 1.0.0
generated: "2023-07-04T15:48:19.259749785Z"
