apiVersion: v1
kind: PersistentVolume
metadata:
  name: node-shared-rabbit-volume
  labels:
    system: rabbit
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/shared-k8s/rabbit"
