apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "portability-gateway.fullname" . }}-listener
  labels:
    {{- include "portability-gateway.labels" . | nindent 4 }}-listener
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.listener.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "portability-gateway.selectorLabels" . | nindent 6 }}-listener
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "portability-gateway.selectorLabels" . | nindent 8 }}-listener
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "portability-gateway.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}-listener"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          env:
            {{- range .Values.configs }}
            - name: {{ .name | quote }}
              valueFrom:
                configMapKeyRef:
                  name: {{ .refName | quote }}
                  key: {{ .name | quote }}
            {{- end }}

            {{- range .Values.secrets }}
            - name: {{ .name | quote }}
              valueFrom:
                secretKeyRef:
                  name: {{ .refName | quote }}
                  key: {{ .name | quote }}
            {{- end }}
              
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
