apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name  }}
  labels:
    {{- include "datora-consumption-microservice.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      
  selector:
    {{- include "datora-consumption-microservice.selectorLabels" . | nindent 4 }}
