apiVersion: v1
kind: Service
metadata:
  name: {{ include "manager-api.fullname" .  }}
  labels:
    {{- include "manager-api.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      
  selector:
    {{- include "manager-api.selectorLabels" . | nindent 4 }}
