apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "activation-gateway-listener.fullname" . }}
  labels:
    {{- include "activation-gateway-listener.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "activation-gateway-listener.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "activation-gateway-listener.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "activation-gateway-listener.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
              
          env:
            # SERVER
            - name: NODE_ENV
              valueFrom:
                configMapKeyRef:
                  name: activation-gateway-listener
                  key: NODE_ENV

            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: activation-gateway-listener
                  key: PORT

            - name: BASE_URI
              valueFrom:
                configMapKeyRef:
                  name: activation-gateway-listener
                  key: BASE_URI
            
            # DATABASE
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: activation-gateway-listener
                  key: DB_PORT

            - name: DB_DIALECT
              valueFrom:
                configMapKeyRef:
                  name: activation-gateway-listener
                  key: DB_DIALECT

            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: activation-gateway-listener
                  key: DB_NAME

            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: activation-gateway-listener
                  key: DB_HOST

            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: activation-gateway-listener
                  key: DB_USERNAME

            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: activation-gateway-listener
                  key: DB_PASSWORD

            # APIS
            - name: API_MAIL
              valueFrom:
                configMapKeyRef:
                  name: activation-gateway-listener
                  key: API_MAIL

            - name: API_AUTHENTICATION
              valueFrom:
                configMapKeyRef:
                  name: activation-gateway-listener
                  key: API_AUTHENTICATION

            - name: API_RECHARGE_AND_PLAN
              valueFrom:
                configMapKeyRef:
                  name: activation-gateway-listener
                  key: API_RECHARGE_AND_PLAN

            - name: API_FINANCIAL_TRANSACTION
              valueFrom:
                configMapKeyRef:
                  name: activation-gateway-listener
                  key: API_FINANCIAL_TRANSACTION

            # RABBIT
            - name: RABBIT_HOST
              valueFrom:
                configMapKeyRef:
                  name: activation-gateway-listener
                  key: RABBIT_HOST

            - name: RABBIT_PORT
              valueFrom:
                configMapKeyRef:
                  name: activation-gateway-listener
                  key: RABBIT_PORT

            - name: RABBIT_USER
              valueFrom:
                secretKeyRef:
                  name: activation-gateway-listener
                  key: RABBIT_USER

            - name: RABBIT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: activation-gateway-listener
                  key: RABBIT_PASSWORD

            # TOKEN
            - name: ENCRYPTION_KEY
              valueFrom:
                secretKeyRef:
                  name: activation-gateway-listener
                  key: ENCRYPTION_KEY

            - name: ENCRYPTION_IV
              valueFrom:
                secretKeyRef:
                  name: activation-gateway-listener
                  key: ENCRYPTION_IV
                        
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
