apiVersion: v1
kind: PersistentVolume
metadata:
  name: node-shared-mongo-volume
  labels:
    system: mongo
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/shared-k8s/mongo"
