---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: financial-transaction-gateway

data:
  # TOKEN
  ENCRYPTION_KEY: ""
  ENCRYPTION_IV: ""
  # DATABASE
  DB_USERNAME: ""
  DB_PASSWORD: ""
