name: CI - github

on: push

jobs:
  Build-and-push-image:
    runs-on: ubuntu-latest
    container:
        image: ghcr.io/pagtel-devops/charts-repository:sha-cda786b
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    #- name: Login to Dockerhub
    #  uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
    #  with:
    #    registry: ${{ env.REGISTRY }}
    #    username: ${{ secrets.DOCKERHUB_USERNAME }}
    #    password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: checkout
      uses: actions/checkout@v2
      whit:
        fetch-depth: 0
        
    - name: Configure Git
      run: |
        git config user.name "${{ secrets.DOCKERHUB_USERNAME }}"
        git config user.mail "${{ secrets.DOCKERHUB_USERNAME }}@pagtel.com.br"
        
    - name: install Helm
      uses: Azure/setup-helm@v3
      with:
        version: latest

    - name: custom packaging
      run: |
        mkdir -p ./public/default  

        helm package default/* --destination ./public/default 

        helm repo index --url 
        
    - name: Helm Chart Releaser
      uses: helm/chart-releaser-action@v1.5.0
      with:
        charts_dir: charts-repository/default
        charts_repo_url: https://github.com/Pagtel-DevOps/charts-repository/default
      env: 
        CR_TOKEN: "${{ secrets.DOCKERHUB_TOKEN }}"
      
        
