name: CI - github

on: push

jobs:
  Build-and-push-image:
    runs-on: ubuntu-latest
    container:
        image: ghcr.io/pagtel-devops/charts-repository:sha-cda786b
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
   
    - name: custom packaging
      run: |
        helm lint default/*
        
        mkdir -p ./default/default-chart  

        helm package default/* --destination ./default/default-chart 

        helm repo index --url https://github.com/Pagtel-DevOps/charts-repository ./default/default-chart
        
  
