name: CI - github

on: push
    
    
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
       
    #tags: 
      #  - 'v*.*.*'
      #  - ^v.*-.*$
jobs:
  Build-and-push-image:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    # Build
    
    - name: Login to Dockerhub
      uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Docker Metadata action 
      id: docker_meta
      uses: docker/metadata-action@507c2f2dc502c992ad446e3d7a5dfbe311567a96
      with: 
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: |
          type=ref,event=branch
          type=sha
    
    - name: QEMU          
      uses: docker/setup-qemu-action@v1

    - name: Build and push Docker images
      uses: docker/build-push-action@37abcedcc1da61a57767b7588cb9d03eb57e28b3
      with:
        context: .
        platforms: linux/amd64
        push: true
        tags: ${{ steps.docker_meta.outputs.tags }}
        labels: ${{ steps.docker_meta.outputs.labels }}
